### ISSUE TITLE
dlopen failed: library "libomp.so" not found

### ISSUE THREAD

**Issue by ithour** [CoelisMyName/sox-for-android#1]

**Comment by CoelisMyName** [comment]
if this happened in runtime, you have to copy "libomp.so" from ndk to jniLibs.
Sdk/ndk/${ndk-version}/toolchains/llvm/prebuilt/${your-host}/lib64/clang/12.0.8/lib/linux/${linux-arch}
就这么说吧，Android Studio有点懒，不知道把libomp.so打包进来，你需要从ndk里复制出libomp.so到你项目里

**Comment by ithour** [comment]
@CoelisMyName 谢谢指导， 但是我看ndk 里面只看到了libomp.a 文件，复制过去还是相同的错误

**Comment by CoelisMyName** [comment]
奇怪，你的ndk是不是不完整，你的ndk版本号和你开发的Android API等级多少？
你必须确保libsox.so和libomp.so在同一目录下，确保ABI相同。

**Comment by CoelisMyName** [comment]
另外，如果你没有libomp.so，那也不太可能能构建libsox.so成功

**Comment by ithour** [comment]
@CoelisMyName  ndk 试过r20b 、r17c  Android API 27    我的libsox.so 和libomp.a 是在同一目录，CMakeLists 是否需要添加什么代码么

**Comment by ithour** [comment]
我这边使用的libsox.so 是从你项目中复制过来的，使用你的脚本编译 ，是失败的，可能还是环境问题，这边执行autoreconf -i

$ autoreconf -i
configure.ac:44: warning: The preprocessor macro `STDC_HEADERS' is obsolete.
configure.ac:44:   Except in unusual embedded environments, you can safely include all
configure.ac:44:   ISO C90 headers unconditionally.
Makefile.am:18: error: 'pkgconfig_DATA' is used but 'pkgconfigdir' is undefined
autoreconf: error: automake failed with exit status: 1

**Comment by CoelisMyName** [comment]
> 我这边使用的libsox.so 是从你项目中复制过来的，使用你的脚本编译 ，是失败的，可能还是环境问题，这边执行autoreconf -i
> 
> $ autoreconf -i configure.ac:44: warning: The preprocessor macro `STDC_HEADERS' is obsolete. configure.ac:44: Except in unusual embedded environments, you can safely include all configure.ac:44: ISO C90 headers unconditionally. Makefile.am:18: error: 'pkgconfig_DATA' is used but 'pkgconfigdir' is undefined autoreconf: error: automake failed with exit status: 1

你编译的是什么环境，我编译的时候是在windows上用msys2

**Comment by ithour** [comment]
我也是

**Comment by ithour** [comment]
你使用的sox 是哪版本的呢

**Comment by CoelisMyName** [comment]
sox代码我就是用这个仓库的，ndk我是通过Android Studio下载的23.1.7779620，你可能要下载最新的ndk，起码必须有libomp.so（如果用我提供的so），或者你必须重新静态构建。

**Comment by ithour** [comment]
好的，我这边再试试，感谢
